# Store file in your working directory
# and then read into a 

file_data <- read.csv("data_brexit_referendum.csv")
head(file_data)

#What data type is this file?
class(file_data)

# Lets look at the structure of the file
str(file_data)

# --------------------------------------------------------------------------------------
# Dealing with missing data
# --------------------------------------------------------------------------------------

# The original data has missing values
# represented by the number "-1"
# We need to search for these and replace them

# Check for values in "Leave" column where
# value = -1
sum(file_data$Leave[file_data$Leave == -1])

# replace this with NA
file_data$Leave[file_data$Leave == -1] <- NA

# Verify that the replace happened
sum(file_data$Leave[file_data$Leave == -1])

# View the records with NA
na_records <- file_data[!complete.cases(file_data),]
na_records

# Same count as when values were -1
nrow(na_records)


library(mice)
# 15 records have missing NI address
# 10 have missing type
md.pattern(file_data)

library(VIM)

# Looks like the missing values are all in this 1 column
# for "Leave". We're not going to use it for now
# so we'll leave it as it is
missing_values <- aggr(file_data, prop = FALSE, numbers = TRUE)

# Lets look at the proportion of voters who
# are in favour of leaving the E.U.
# I'm creating a new variable to store this information in
file_data$Proportion <- file_data$Leave / file_data$NVotes
file_data$Proportion

# Store remain or leave in the Vote variable
# Note that 
file_data$Vote[file_data$Proportion <= 0.5] <- "Remain"
file_data$Vote[file_data$Proportion > 0.5] < "Leave"
file_data$Vote

attach(file_data)
# Note that we still need to refer to the full path to the variable for
# part of the statement

# Need to convert to character from factor before we can convert the variable

file_data$RegionName <- as.character(RegionName)
str(file_data)
file_data$RegionName[RegionName == "London"] <- "L" # Check that this has happened
file_data$RegionName[RegionName == "North West"] <- "NW" 
file_data$RegionName[RegionName == "North East"] <- "NE" 
file_data$RegionName[RegionName == "South West"] <- "SW" 
file_data$RegionName[RegionName == "South East"] <- "SE" 
file_data$RegionName[RegionName == "East Midlands"] <- "EM" 
file_data$RegionName[RegionName == "West Midlands"] <- "WM" 
file_data$RegionName[RegionName == "East of England"] <- "EE" 
file_data$RegionName[RegionName == "Yorkshire and The Humber"] <- "Y" 

# Now we have a new variable of interest called proportion
# and we will now focus on this variable

# Lets view the summary of the data

# We can see that this shows relevant summaries of the data
# and it is tailored for each data type
summary(file_data)

# We're not able to directly reference this data because some is non-numeric
# and does not contai nwhat we want to view such as minimum, first quartile, median, mean, third quartile
# but we can use sapply() and check whether each data variable is a numer ic varibale or not
# eg to check whether proportion is a numeric value or not
is.numeric(file_data$Proportion)
is.numeric(file_data$RegionName)

# Use double-tab for structure of sapply()
numeric_variable_list <- sapply(file_data, is.numeric)
numeric_variable_list

# We can use this logic to create a subset of the data
numerical_data <- file_data[numeric_variable_list]
colnames(numerical_data)

# Remove the ID field as it has no meaning
numeric_variable_list["ID"] <- FALSE

# Then remove this again from the main file_data dataset
numerical_data <- file_data[numeric_variable_list]
colnames(numerical_data)

# We can use the lapply() function to return a named list
# where each list member has a corresponding name
lapply(numerical_data, summary)

?cbind()
# cbind() combines objects by rows and columns
# so we can use this function to create a dataset
# of the lapply() output

# do.call() function will allow us to 
# apply the cbind() to each element generated by lapply()
?do.call
# do.call(what, args, quote = FALSE, envir = parent.frame())
numerical_summary <- do.call(cbind, lapply(numerical_data, summary))

# Error message shows additional ine - caused by NA's
# We could drop NA's but that will only fix this one issue
# Instead we need to go back to the source and drop the NA's

file_data <- file_data[complete.cases(file_data),]
numerical_data <- file_data[numeric_variable_list]
numerical_summary <- do.call(cbind, lapply(numerical_data, summary))
numerical_summary

# We can do a swap with summary values as columns and variables as rows 
# then we use rbind()
alt_numerical_summary <-  do.call(rbind, lapply(numerical_data, summary))
alt_numerical_summary

# Now we can apply some computations
# such as finding range between wards with the least and most proportions of votes in
# favour of leaving (0.6681), which may be useful to interpret the big difference among the
# types of wards we may find in the UK. If we want to know which wards are being used to
# get to this result, we can search for the wards with the least and most proportion of votes

# We can use this data to show specific values such as 
# the max proportion value - max percent of those who voted to leave
# prop = leave / no of votes in ward
numerical_summary["Max.", "Proportion"]

# And the min proportion value can show us 
numerical_summary["Min.", "Proportion"]

numerical_summary["Max.", "Proportion"] - numerical_summary["Min.", "Proportion"]

# Lets look at values of those who wanted to leave and stay
display_variables <- c("NoQuals", "Proportion", "AdultMeanAge", "L4Quals_plus", "RegionName")

# Values show that those with mean age of 46.9 and 20% no qualifications
# and 27.3 with level 4 quals (degree and above) voted to leave
file_data[which.max(file_data$Proportion), display_variables]

# Those who wanted to stay were younger with better qualifications
file_data[which.min(file_data$Proportion), display_variables]

table(file_data$RegionName)

?prop.table
# table value expressed as fractions
prop.table(table(file_data$RegionName))

barplot(height = prop.table(table(file_data$RegionName)),
        main = "Vote proportion by Region", 
        ylab = "Frequency", 
        xlab = "Region",
        col = "white")

# chart where each point Each point represents a ward
# observation, and it shows the proportion of Leave votes for each ward, arranged in
# vertical lines corresponding to RegionName and coloured by the proportion of white
# population for each ward. As you can see, we have another interesting finding; it seems that
# the more diversified a ward's population is (seen in the darker points), the more likely it is
# for the ward to vote in favor of remaining in the EU (a lower Proportion value).

# Creates the plot
install.packages("ggplot2")
# Colour each chart point witha colour palette
install.packages("viridis")
library(ggplot2)
library(viridis)

plot <- ggplot(file_data, aes(x = RegionName, y = Proportion, color = White))
plot <- plot + geom_point() + scale_color_viridis()
print((plot))

hist(file_data$NoQuals, main = "Histogram for NoQuals", xlab = "")
hist(file_data$L4Quals_plus, main = "Histogram for L4 qualifications +", xlab = "")
hist(file_data$MeanAge, main = "Histogram for mean adult age", xxlab = "")

# Now that we understand more about qualifications
# we'll have a look at the scatter plots for distribution
# both charts resemble each other
plot(x = file_data$NoQuals, y = file_data$AdultMeanAge, ylab = "Adult Mean age", xlab = "No qualifications")
plot(x = file_data$L4Quals_plus, y = file_data$AdultMeanAge, ylab = "Adult mean age", xlab = "L4 qualifications+")


variables_of_interest <- c("AdultMeanAge", "White", "Owned", "NoQuals", "L4Quals_plus", "Unemp", "HigherOccup", "Deprived", "Proportion")
pairs(file_data[variables_of_interest])


# Now lets look at soem charts in more detail
plot <- ggplot(file_data, aes(x = NoQuals, y = AdultMeanAge, color = Proportion))
plot <- plot + stat_smooth(method = "lm", col = "darkgrey", se = FALSE)
plot <- plot + scale_color_viridis()
plot <- plot + geom_point()
print(plot)